api_platform:
    mapping:
        paths: ['%kernel.project_dir%/config/resources/']

    enable_nelmio_api_doc: true
    enable_swagger: true
    enable_swagger_ui: false
    swagger:
        api_keys:
            apiKey:
                name: 'Authorization'
                type: 'header'
