nelmio_api_doc:
    documentation:
        info:
            title: Notification Hub
            description: ''
            version: false
    routes: # to filter documented routes
        path_patterns:
            - ^/api/(jwt|channel|line)
