security:
    encoders:
        App\Entity\User:
            algorithm: bcrypt

    providers:
        default:
            entity:
                class: App\Entity\User
                property: usernameCanonical

    firewalls:
        dev:
#            pattern: ^/(_(profiler|wdt)|css|images|js)/
            pattern: ^/_((profiler|wdt)|css|images|js)
            security: false

        login:
            pattern:  ^/api/jwt
            stateless: true
            anonymous: true
            provider: default
            form_login:
                check_path:               /api/jwt/token
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false

        docs:
            pattern: ^/api/doc
            provider: default
            http_basic: ~

        register:
            pattern:  ^/api/account$
            anonymous: true

        api:
            pattern:   ^/api
            stateless: true
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

    access_control:
        - { path: ^/api/jwt,          roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/account,      roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api,              roles: IS_AUTHENTICATED_FULLY }